[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "functions"

[build.environment]
  NODE_ENV = "production" 