services:
  - type: web
    name: chat-application
    env: node
    buildCommand: npm install
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 